### ISSUE TITLE
Memory issue

### ISSUE THREAD

**Issue by TangLabsysu2020** [ludvb/xfuse#32]
Hello,
    Thanks for the useful approach. I am trying to run xfuse on 5 visium slide with a 16GB GPU. But always get a memory error (CUDA out of memory). Can i adjust the parameters to reduce the required memory used by xfuse? or can i run the 5 slide separately, if i run them separately, will the results be inaccurate?

**Comment by ludvb** [comment]
Hi,

There are a few options you can tweak in your config.toml to reduce memory consumption:

1. optimization.batch_size: the number of tissue patches in each mini-batch
2. optimization.patch_size: the size of each tissue patch
3. xfuse.network_depth: the number of U-net down- and upsampling steps
4. xfuse.network_width: the number of channels in the final U-net layer

I would suggest first reducing the batch_size to perhaps 2 or 3 (default is 4), as that should have minimal impact on results. Reducing the patch_size may sometimes have a detrimental effect on learning but is usually fine if the tissue has clear morphology. Just keep in mind that the patch_size should preferably be k * 2 ** network_depth for some k. I would try to avoid adjusting the network_depth and network_width, as doing so would reduce the capacity of the network.

With 16 GB of video RAM, I think you should be fine just adjusting the batch_size. The size of the dataset should not impact memory consumption, so it should be fine to run on all 5 slides simultaneously.

Let me know how it goes!

**Comment by TangLabsysu2020** [comment]
Hi,
    Thanks for your advise. When i reduce the batch_size from 3 to 2. the memory used by xfuse was decreased, and i run xfuse successfully on my server now. Thanks!

**Comment by ludvb** [comment]
Awesome, thanks for reporting back!
