### ISSUE TITLE
xfuse not found after installing

### ISSUE THREAD

**Issue by JunMa11** [ludvb/xfuse#34]
Dear @ludvb ,

Thanks for sharing this great work.

After installing the xfuse, I met the following error when converting the data to the right format:

![1641231605(1)](https://user-images.githubusercontent.com/19947331/147961875-ae90d138-f1ba-4af7-9710-47937da0b24e.png)

I'm sure that `xfuse` has been installed.

![1641231875(1)](https://user-images.githubusercontent.com/19947331/147962304-dd799b17-079a-4dfb-b5a6-db328b56572c.png)

Could you please give me some suggestions about how to fix this problem?

**Comment by ludvb** [comment]
Hi,

Pip usually installs executables to `~/.local/bin`, could you check if the xfuse executable is there? If so, you may need to add that directory to your PATH environment variable (`export PATH=~/.local/bin:$PATH`). If you're in a virtual environment, I suspect the install directory may be different, though. An idea could be to use mlocate to find the executable (something like `sudo updatedb && locate -r 'xfuse$'` will probably work).

Let me know how it goes!

**Comment by JunMa11** [comment]
Thank you so much for your help:)
The problem has been solved by adding the xfuse path to PATH environment.

**Comment by ludvb** [comment]
Great! Thanks for reporting back :)
