### ISSUE TITLE
Which results to look at?

### ISSUE THREAD

**Issue by jianhuupenn** [ludvb/xfuse#39]
Hi there,
I have another question about the results. The output has 3 images for each gene in the gene map folder, for example, 
CD3D_invcv+.jpg,
CD3D_mean.jpg,
CD3D_stdv.jpg
They all look very similar. Which one would you recommend me to use as the enhanced gene expression?

Thanks.

**Comment by fuerzhou** [comment]
Hi @ludvb,

I have run Xfuse on my data and got the gene maps, including the mean, invcv+ and stdv results. They look nice and many of the genes show patterns that make sense! I wonder if I can get the metrics/numbers of the predicted gene expressions of each pixel for further analysis. Or do I need to extract the intensities from the jpgs?

Thank you!
Yuzhou

**Comment by ludvb** [comment]
Hi @fuerzhou, there should be an option `writer = "tensor"` that you can set in the toml config for the gene maps analysis which will save pickled torch.Tensors instead. Keep in mind that the output files can get quite large, since the tensor writer saves all monte carlo samples (i.e., not just the mean or stdv as the jpg writer). To try it out on a limited number of genes, you can use the `gene_regex` option to specify which genes to save.

**Comment by fuerzhou** [comment]
That's great to hear. Thank you @ludvb !

**Comment by fuerzhou** [comment]
Hi @ludvb, I tried the option `writer = "tensor"` and got .pt files for the genes specified in `gene_regex`. However, it seems that the .pt files are not readable and are for further training. Could you please provide further suggestions on how to get the prediction results from this? 

Thank you again!
Yuzhou

**Comment by ludvb** [comment]
Hi @fuerzhou, the .pt files contain raw sample data as torch tensors, so some processing may be necessary. You can load them from a python repl like this:
```
import torch
x = torch.load("/path/to/sample.pt")
```

**Comment by fuerzhou** [comment]
Hi @ludvb, thank you very much for the info. I have successfully read the predicted data. For our data, the tensor of each gene has three dimensions and the first dimension is 10. This results in 10 predicted gene expression profiles. If I understand it correctly, the final mean, invcv+ and stdv are calculated from these 10 samples?

**Comment by ludvb** [comment]
Yes @fuerzhou that is correct!
